import type { ActivityTemplate } from "@/lib/planning/types";

export const ACTIVITY_TEMPLATES: ActivityTemplate[] = [
  {
    id: "coffee_chat",
    title: "Coffee chat",
    vibeTarget: 35,
    budget: "low",
    durationBand: "45m",
    durationMinutes: 45,
    indoorOutdoor: "indoor",
    goodFor: ["talk"],
    categories: ["coffee"],
    slotStyle: "weekday_evening",
    locationBlurb: "Quiet café with seating",
  },
  {
    id: "walk_coffee",
    title: "Walk + coffee",
    vibeTarget: 45,
    budget: "low",
    durationBand: "90m",
    durationMinutes: 75,
    indoorOutdoor: "mixed",
    goodFor: ["talk", "active"],
    categories: ["walk", "coffee"],
    slotStyle: "weekend_morning",
    locationBlurb: "Park loop ending near coffee",
  },
  {
    id: "lunch",
    title: "Lunch catch-up",
    vibeTarget: 55,
    budget: "mid",
    durationBand: "90m",
    durationMinutes: 90,
    indoorOutdoor: "indoor",
    goodFor: ["talk"],
    categories: ["lunch"],
    slotStyle: "weekday_evening",
    locationBlurb: "Casual lunch spot",
  },
  {
    id: "dinner",
    title: "Dinner",
    vibeTarget: 65,
    budget: "high",
    durationBand: "2-3h",
    durationMinutes: 150,
    indoorOutdoor: "indoor",
    goodFor: ["talk"],
    categories: ["dinner"],
    slotStyle: "weekend_afternoon",
    locationBlurb: "Restaurant with good conversation seating",
  },
  {
    id: "sport",
    title: "Sport session",
    vibeTarget: 80,
    budget: "mid",
    durationBand: "90m",
    durationMinutes: 90,
    indoorOutdoor: "mixed",
    goodFor: ["active"],
    categories: ["sport"],
    slotStyle: "weekend_morning",
    locationBlurb: "Court / gym / outdoor pitch",
  },
  {
    id: "culture",
    title: "Culture outing",
    vibeTarget: 40,
    budget: "mid",
    durationBand: "2-3h",
    durationMinutes: 120,
    indoorOutdoor: "indoor",
    goodFor: ["talk"],
    categories: ["culture"],
    slotStyle: "weekend_afternoon",
    locationBlurb: "Museum or cinema area",
  },
  {
    id: "cowork",
    title: "Cowork sprint",
    vibeTarget: 30,
    budget: "low",
    durationBand: "2-3h",
    durationMinutes: 120,
    indoorOutdoor: "indoor",
    goodFor: ["talk"],
    categories: ["cowork"],
    slotStyle: "weekday_evening",
    locationBlurb: "Library or calm cowork space",
  },
];

export function getTemplateById(id: string): ActivityTemplate | undefined {
  return ACTIVITY_TEMPLATES.find((t) => t.id === id);
}
